system ice/iceMisilTurbo
{
    category                                    ice
    technique 
    {
        keep_local                              true
        emitted_emitter_quota                   20
        material                                iceflame
        default_particle_width                  6
        default_particle_height                 6
        default_particle_depth                  6
        spatial_hashing_cell_dimension          1
        renderer                                Billboard
        {
        }
        emitter                                 Point 
        {
            emission_rate                       80
            angle                               0
            time_to_live                        2
            mass                                10
            velocity                            20
            direction                           0 0 -1
            orientation                         1 0 0 1
            auto_direction                      true
        }
        affector                                Gravity 
        {
            position                            1 0 0
            gravity                             10
        }
        affector                                Scale 
        {
            xyz_scale                           -3
        }
    }
}
